DROP TABLE IF EXISTS accounts;
CREATE TABLE accounts
(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR
(100) NOT NULL,
    balance DEC
(15,2) NOT NULL,
    PRIMARY KEY
(id)
);

INSERT INTO accounts
    (name, balance)
VALUES('Bob', 10000)
RETURNING *;

----------------- BEGIN
BEGIN;
    INSERT INTO accounts
        (name, balance)
    VALUES('Alice', 10000)
    RETURNING *;

    -- When select then we see one item
    SELECT *
    FROM accounts;
    ----------------- END


    ------- USING BEGIN AND COMMIT
    BEGIN;
        INSERT INTO accounts
            (name, balance)
        VALUES('LongLe', 20000)
        RETURNING *;

        SELECT *
        FROM accounts;

        COMMIT;
        ------- USING BEGIN AND COMMIT





        /* START a transaction */
        BEGIN;

            -- deduct 1000 from account 1
            UPDATE accounts
        SET balance = balance - 1000
        WHERE id = 1;
            -- add 1000 to account 2
            UPDATE accounts
        SET balance = balance + 1000
        WHERE id = 2;

            -- View new update
            SELECT *
            FROM accounts;

            COMMIT;
            /* END a transaction */



            ---------------
            INSERT INTO accounts
                (name, balance)
            VALUES
                ('Jack', 0);


            --- Demo ROLLBACK;
            BEGIN;

                UPDATE accounts
            SET balance = balance - 1500
            WHERE id = 1;

                UPDATE accounts
            SET balance = balance + 1500
            WHERE id = 3;

                -- View new update
                SELECT *
                FROM accounts;

                ROLLBACK;

